kind: pipeline
type: docker
name: default
trigger:
  branch:
    - develop

steps:
- name: Version check
  image: jguyomard/hugo-builder
  commands:
  - echo "Checking Hugo version."
  - hugo version
  environment:
    VERSION: 0.67.0

- name: Build swiso.org version
  image: jguyomard/hugo-builder
  commands:
  - mkdir -p public/swiso-org
  - hugo -b https://develop.swiso.org -d public/swiso-org
  - mkdir -p public/switching-software
  - hugo -b https://develop.switching.software -d public/switching-software

- name: Upload
  image: jguyomard/hugo-builder
  commands:
  - eval `ssh-agent -s`
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rv -e "ssh -p 22" public/swiso-org/ drone@swiso.org:/home/drone/www/swiso-org/develop --checksum --delete-delay
  - rsync -rv -e "ssh -p 22" public/switching-software/ drone@swiso.org:/home/drone/www/switching-software/develop --checksum --delete-delay
  environment:
    SSH_KEY:
      from_secret: drone_ssh_key