baseURL= "https://switching.software/"
title= "switching.software"
description= "" 
DefaultContentLanguage = "en"

[taxonomies]
    replace = "replaces"
    tag = "tags"

[permalinks]
    replaces = "/replace/:slug"

[languages]
    [languages.en]
        title = "switching.software"
        weight = 1
    [languages.de]
        title = "switchingsocial.de"
        weight = 2

